Fix unused variable warning when JIT and SYSTEM are enabled
When building with make 'ENABLE_JIT=1 ENABLE_SYSTEM=1', the following
error is observed:

src/emulate.c:45:13: error: ‘need_clear_block_map’ defined but not used [-Werror=unused-variable]
   45 | static bool need_clear_block_map = false;
      |             ^~~~~~~~~~~~~~~~~~~~

Fix this by guarding the 'need_clear_block_map' definition with the
RV32_HAS(SYSTEM) and !RV32_HAS(JIT) macros. This ensures the variable
is only defined when the macros indicate it is needed.