Fix compiler error when MOP_FUSION is disabled
When using 'make ENABLE_MOP_FUSION=0', the following error is observed:

src/emulate.c:714:13: error: ‘match_pattern’ defined but not used [-Werror=unused-function]
  714 | static void match_pattern(riscv_t *rv, block_t *block)
      |             ^~~~~~~~~~~~~

Fix this by guarding the match_pattern function definition with
RV32_HAS(MOP_FUSION) macro. This ensures the function is only defined
when the MOP_FUSION is enabled.